{% set name = "pidcalib2" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pidcalib2-{{ version }}.tar.gz
  sha256: c49c3cccef5a8274242b32d63de0283751a9a76084502220de53b38b6f0d66e2

build:
  number: 0
  noarch: python
  entry_points:
    - pidcalib2.make_eff_hists = pidcalib2.make_eff_hists:main
    - pidcalib2.ref_calib = pidcalib2.ref_calib:main
    - pidcalib2.merge_trees = pidcalib2.merge_trees:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - boost-histogram
    - logzero
    - numpy
    - pandas
    - python >=3.6
    - tqdm
    - uproot
    - uproot3

test:
  imports:
    - pidcalib2
    - pidcalib2.tests
  commands:
    # Fails as there is a dependency on XRootD 5.2 but that's only available for CentOS 7+
    # - pip check
    - pidcalib2.make_eff_hists --help
    # Can't be tested without installing ROOT
    # - pidcalib2.ref_calib --help
    # - pidcalib2.merge_trees --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-rta/pidcalib2
  summary: A set of tools for estimating LHCb PID efficiencies
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dcervenkov
    - chrisburr
